### PR TITLE
Ignore issues if they are disabled

### PR DESCRIPTION
**Pull request by shama**
Some repos have issues disabled (being managed outside of github) but still want to haunt pull requests. This PR will ignore issues if they are disabled.

Here is the error I received on a repo that has issues disabled:

```
/var/www/haunt/lib/repo.js:158
            .map(function (issue) { return !issue.pull_request.html_url && iss
                                                              ^
TypeError: Cannot read property 'html_url' of undefined
    at Repo.getIssues (/var/www/haunt/lib/repo.js:158:63)
```

and the contents of `issues`: `[ { message: 'Issues are disabled for this repo' } ]`

Thanks!

### CODE REVIEW

**Comment by fat** [comment]
hm... were you defining issue tests though? It shouldn't try to get issues without issue tests?

**Comment by fat** [comment]
i can't accept this patch, because not all issues have a pull request object

**Comment by shama** [comment]
Really? I thought non pull request issues had `pull_request: { patch_url: null, html_url: null, diff_url: null }`?
I ran it over all 515 issues (414 non PR issues) on joyent/node and didn't hit a problem.

Here is my test and the command/output ran on a repo where issues are disabled: https://gist.github.com/3185723

**Comment by fat** [comment]
hmm.. it's possible im mistaken! I'll double check tonight

**Comment by fat** [comment]
confirmed, you are totally right! thanks :heart:

**Pull request merged**
