### PR TITLE
Add commentOnDiff method

### LINKED ISSUE #2: Feature request: ability to comment on pull request diffs
Adding the ability to comment on specific lines of pull request diff would, for example, allow linters and automated test suites to point out specific failures in context.

### PR DESCRIPTION
**Pull request by shama**
Fixes #2

Enables commenting on a line of a diff with:

``` javascript
pull.commentOnDiff({
    body: 'comments all up in ya code',
    commit_id: 'fd9e30492ae661058afe532ed6cfc0cb6d1d644f',
    path: 'relative/path/to/my/file.js',
    position: 4
})
```

Or if you know a comment id, you can reply with:

``` javascript
pull.commentOnDiff({
    body: 'ya I agree',
    in_reply_to: 123
})
```

Cheers!

### CODE REVIEW

**Comment by fat** [comment]
do you think the comment on diff method should be augmented onto a file object? instead of being on the root of the pull?

So the api would be like `file.comment('This is a comment', lineNumber);`

**Comment by shama** [comment]
Oh good call, that would be better. I'll update the PR. Thanks!

**Comment by shama** [comment]
Updated the PR.

`in_reply_to` will no longer work as shown above. Do think it would be useful to add `issue.files[*].comments` and `issue.files[*].comments[*].reply('comment here')` as well? So comments on diffs could also be handled?

**Comment by fat** [comment]
this looks awesome! The reply api sounds good to me :) thanks!

**Comment by fat** [comment]
cool - thanks again! I republished as 1.1.0

**Pull request merged**
